version: '2'
services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/nginx.conf
            - ./docker/logs/nginx:/var/log/nginx
            - .:/var/www/html
        links:
            - php:php
        command: nginx -c /nginx.conf
    php:
        build:
            context: docker/php
            args:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
            # Set here your timezone using one of this: http://php.net/manual/en/timezones.php
=======
>>>>>>> 2c3759a... Add the timezone as an argument in the docker-compose. For that, need to use v2 of docker-compose (with version >= 1.6.0)
=======
>>>>>>> 028be7b... Add the timezone as an argument in the docker-compose. For that, need to use v2 of docker-compose (with version >= 1.6.0)
=======
            # Set here your timezone using one of this: http://php.net/manual/en/timezones.php
>>>>>>> c40dd2d... Add comment
                timezone: 'Europe/Monaco'
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        #links:
            # - "postgres:rdbms"
            # - "mariadb:rdbms"
        env_file:
            - ./docker/php/env
            # Comment non-used DBMS lines
            # If all DBMS are commented out, sqlite will be used as default
            # - ./docker/postgres/env
            # - ./docker/mariadb/env
    #postgres:
    #    image: postgres:9
    #    ports:
    #        - "5432:5432"
    #    volumes:
    #        - ./docker/data/pgsql:/var/lib/postgresql/data
    #    env_file:
    #        - ./docker/postgres/env
    #mariadb:
    #    image: mariadb:10
    #    ports:
    #        - "3306:3306"
    #    volumes:
    #        - ./docker/data/mariadb:/var/lib/mysql
    #    env_file:
    #        - ./docker/mariadb/env
