wallabag_annotation:
  type : rest
  resource: "@WallabagAnnotationBundle/Resources/config/routing_annotations.yml"
  prefix: "%base_path%/"

wallabag_import:
    resource: "@WallabagImportBundle/Controller/"
    type: annotation
    prefix: "%base_path%/import"

wallabag_api:
    resource: "@WallabagApiBundle/Resources/config/routing.yml"
    prefix: "%base_path%/"

app:
    resource: "@WallabagCoreBundle/Controller/"
    type: annotation
    prefix: "%base_path%/"

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "%base_path%/api/doc"

rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : "%base_path%/api"

homepage_main:
    path: "%base_path%/"
    defaults:
        _controller: WallabagCoreBundle:Entry:showUnread
        page: 1

homepage:
    path: "%base_path%/{page}"
    defaults:
        _controller: WallabagCoreBundle:Entry:showUnread
        page : 1
    requirements:
        page: \d+

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: "%base_path%/"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    prefix: "%base_path%/"

craue_config_settings_modify:
    path: "%base_path%/settings"
    defaults:
        _controller: CraueConfigBundle:Settings:modify
